(function initPondAchievementConfig(root, factory) {
  const achievements = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = achievements;
  else root.PondAchievementConfig = achievements;
})(typeof globalThis !== "undefined" ? globalThis : window, function makeAchievementConfig() {
  return [
    {
      id: "first_steps",
      name: "First Steps",
      description: "Play your first match.",
      badgeIcon: "R",
      badgeId: "rookie",
      xpReward: 30,
      coinReward: 10,
      conditionType: "gamesPlayed",
      threshold: 1,
    },
    {
      id: "pond_winner",
      name: "Pond Winner",
      description: "Win your first match.",
      badgeIcon: "W",
      badgeId: "first_win",
      xpReward: 80,
      coinReward: 25,
      conditionType: "wins",
      threshold: 1,
    },
    {
      id: "duck_rush",
      name: "Duck Rush",
      description: "Win a match as Duck.",
      badgeIcon: "D",
      badgeId: "duck",
      xpReward: 70,
      coinReward: 20,
      conditionType: "animalWins",
      animal: "duck",
      threshold: 1,
    },
    {
      id: "snake_strike",
      name: "Snake Strike",
      description: "Capture 30 tiles with one Ambush-style attack wave.",
      badgeIcon: "S",
      badgeId: "snake",
      xpReward: 90,
      coinReward: 25,
      conditionType: "animalWave",
      animal: "snake",
      threshold: 30,
    },
    {
      id: "frog_leap",
      name: "Frog Leap",
      description: "Win as Frog or capture objectives with Frog tactics.",
      badgeIcon: "F",
      badgeId: "frog",
      xpReward: 70,
      coinReward: 20,
      conditionType: "animalWins",
      animal: "frog",
      threshold: 1,
    },
    {
      id: "shell_wall",
      name: "Shell Wall",
      description: "Block repeated attacks with Turtle defenses.",
      badgeIcon: "T",
      badgeId: "turtle",
      xpReward: 80,
      coinReward: 20,
      conditionType: "animalDefenses",
      animal: "turtle",
      threshold: 8,
    },
    {
      id: "golden_current",
      name: "Golden Current",
      description: "Reach high income as Carp.",
      badgeIcon: "C",
      badgeId: "carp",
      xpReward: 80,
      coinReward: 20,
      conditionType: "animalIncome",
      animal: "carp",
      threshold: 10,
    },
    {
      id: "builder",
      name: "Builder",
      description: "Build 10 buildings total.",
      badgeIcon: "B",
      badgeId: "builder",
      xpReward: 60,
      coinReward: 20,
      conditionType: "totalBuildingsBuilt",
      threshold: 10,
    },
    {
      id: "architect",
      name: "Architect",
      description: "Upgrade 5 buildings.",
      badgeIcon: "U",
      badgeId: "builder",
      xpReward: 90,
      coinReward: 25,
      conditionType: "totalBuildingUpgrades",
      threshold: 5,
    },
    {
      id: "wave_master",
      name: "Wave Master",
      description: "Capture 50 tiles in one attack wave.",
      badgeIcon: "A",
      badgeId: "warrior",
      xpReward: 120,
      coinReward: 35,
      conditionType: "biggestAttackWave",
      threshold: 50,
    },
    {
      id: "objective_hunter",
      name: "Objective Hunter",
      description: "Capture 5 objectives.",
      badgeIcon: "O",
      badgeId: "objective",
      xpReward: 85,
      coinReward: 25,
      conditionType: "totalObjectivesCaptured",
      threshold: 5,
    },
    {
      id: "comeback_animal",
      name: "Comeback Animal",
      description: "Win after dropping below 10% territory.",
      badgeIcon: "K",
      badgeId: "defender",
      xpReward: 120,
      coinReward: 40,
      conditionType: "comebackWins",
      threshold: 1,
    },
    {
      id: "team_player",
      name: "Team Player",
      description: "Send support to an ally.",
      badgeIcon: "H",
      badgeId: "objective",
      xpReward: 50,
      coinReward: 15,
      conditionType: "supportSent",
      threshold: 1,
    },
    {
      id: "survivor",
      name: "Survivor",
      description: "Survive for 20 minutes.",
      badgeIcon: "V",
      badgeId: "defender",
      xpReward: 110,
      coinReward: 35,
      conditionType: "longestSurvivalTime",
      threshold: 1200,
    },
    {
      id: "lake_emperor",
      name: "Lake Emperor",
      description: "Win 10 matches.",
      badgeIcon: "E",
      badgeId: "emperor",
      xpReward: 220,
      coinReward: 75,
      conditionType: "wins",
      threshold: 10,
    },
  ];
});
