(function initPondAnimalVisuals(root, factory) {
  const visuals = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = visuals;
  else root.PondAnimalVisuals = visuals;
})(typeof globalThis !== "undefined" ? globalThis : window, function makeAnimalVisuals() {
  const animals = {
    duck: {
      id: "duck",
      label: "Duck",
      short: "D",
      badge: "#f2d87a",
      accent: "#ffe9a3",
      dark: "#9a6f27",
      glow: "#fff0b8",
      role: "Fast Expansion",
      difficulty: "Easy",
      terrain: "Open Water",
      weakness: "Reed fights",
      ability: "Flock Rush",
      abilityIcon: "wing",
      attackMotif: "Feather splash",
      defenseMotif: "Nest feather border",
      mapPose: "floating duck",
      victoryTitle: "Pond Rusher",
      lobbyBackdrop: "open water lanes",
      counterplay: "Pressure Duck before it spreads across open water.",
      tooltip: "Duck rushes across open water, expanding faster for a short time.",
    },
    snake: {
      id: "snake",
      label: "Snake",
      short: "S",
      badge: "#5fbf83",
      accent: "#9af0b5",
      dark: "#2e7254",
      glow: "#b5ffd0",
      role: "Ambush Control",
      difficulty: "Medium",
      terrain: "Reeds and Mud",
      weakness: "Slow open water",
      ability: "Ambush",
      abilityIcon: "fang",
      attackMotif: "Fang current",
      defenseMotif: "Reed camouflage shimmer",
      mapPose: "sliding through reeds",
      victoryTitle: "Reed Ambusher",
      lobbyBackdrop: "reeds and mud channels",
      counterplay: "Avoid fighting Snake from reeds or mud when Ambush is ready.",
      tooltip: "Snake prepares a stronger attack from reeds or mud.",
    },
    frog: {
      id: "frog",
      label: "Frog",
      short: "F",
      badge: "#67df8c",
      accent: "#b8f7a4",
      dark: "#34784d",
      glow: "#d5ffc8",
      role: "Mobility Tactics",
      difficulty: "Medium",
      terrain: "Lily Pads",
      weakness: "Open water defense",
      ability: "Big Leap",
      abilityIcon: "lily",
      attackMotif: "Leap splash",
      defenseMotif: "Lily shield splash",
      mapPose: "frog on a lily pad",
      victoryTitle: "Lily Leaper",
      lobbyBackdrop: "lily pad pockets",
      counterplay: "Defend objectives and awkward neutral pockets before Frog leaps in.",
      tooltip: "Frog leaps to capture nearby neutral space.",
    },
    turtle: {
      id: "turtle",
      label: "Turtle",
      short: "T",
      badge: "#6fc5d8",
      accent: "#bdeff0",
      dark: "#2f7280",
      glow: "#d8ffff",
      role: "Shell Defense",
      difficulty: "Easy/Medium",
      terrain: "Mud, rocks, defended borders",
      weakness: "Slow early expansion",
      ability: "Shell Guard",
      abilityIcon: "shell",
      attackMotif: "Heavy shell wave",
      defenseMotif: "Shell-pattern shield",
      mapPose: "slow bobbing shell",
      victoryTitle: "Shell Defender",
      lobbyBackdrop: "marsh stones",
      counterplay: "Soften Turtle with repeated pressure before sending a huge wave.",
      tooltip: "Turtle hardens its borders and reduces incoming attacks.",
    },
    carp: {
      id: "carp",
      label: "Carp",
      short: "C",
      badge: "#f0b44f",
      accent: "#ffd37b",
      dark: "#9b5f22",
      glow: "#ffe2a4",
      role: "Economy Growth",
      difficulty: "Medium",
      terrain: "Open Water and Lily Pads",
      weakness: "Weak if rushed early",
      ability: "Golden Current",
      abilityIcon: "scale",
      attackMotif: "Golden current",
      defenseMotif: "Scale barrier",
      mapPose: "fish in the current",
      victoryTitle: "Golden Current",
      lobbyBackdrop: "gold river flow",
      counterplay: "Pressure Carp early before its economy scales.",
      tooltip: "Carp boosts income and water expansion with a golden current.",
    },
  };

  const buildings = {
    nest: { icon: "nest", label: "Nest", synergy: "Best for Duck", role: "Max energy building", animals: ["duck"], color: "#f2d87a" },
    lilyFarm: { icon: "lily", label: "Lily Farm", synergy: "Best for Frog and Carp", role: "Economy building", animals: ["frog", "carp"], color: "#8ee6a2" },
    reedGuard: { icon: "reeds", label: "Reed Guard", synergy: "Good for Snake and Turtle", role: "Border defense", animals: ["snake", "turtle"], color: "#cddf83" },
    mudTunnel: { icon: "mud", label: "Mud Tunnel", synergy: "Snake only", role: "Reed and mud mobility", animals: ["snake"], color: "#c79662" },
    jumpPad: { icon: "jump", label: "Jump Pad", synergy: "Frog only", role: "Leap mobility", animals: ["frog"], color: "#87d7ea" },
  };

  const objectives = {
    goldenLily: { icon: "goldLily", best: "Frog and Carp", label: "Golden Lily", color: "#e3bd4f" },
    ancientReed: { icon: "reed", best: "Snake and Turtle", label: "Ancient Reed", color: "#91c579" },
    mudSpring: { icon: "mudBubble", best: "Snake and Turtle", label: "Mud Spring", color: "#c39a62" },
    clearWaterShrine: { icon: "shrine", best: "Duck and Carp", label: "Clear Water Shrine", color: "#83dced" },
    deepCurrent: { icon: "current", best: "Duck and Carp", label: "Deep Current", color: "#6fb8f0" },
    turtleCamp: { icon: "shell", best: "Turtle", label: "Turtle Camp", color: "#91b978" },
    crabCamp: { icon: "claw", best: "Attackers", label: "Crab Camp", color: "#df806d" },
    otterCamp: { icon: "paw", best: "Economy players", label: "Otter Camp", color: "#d2a769" },
    dragonflySwarm: { icon: "wing", best: "Scouts and defenders", label: "Dragonfly Swarm", color: "#b58be0" },
  };

  const teams = {
    pond: { label: "Pond Team", badge: "P", color: "#83dced" },
    river: { label: "River Team", badge: "R", color: "#6fb8f0" },
    marsh: { label: "Marsh Team", badge: "M", color: "#91c579" },
    lily: { label: "Lily Team", badge: "L", color: "#e3bd4f" },
    current: { label: "Current Team", badge: "C", color: "#b58be0" },
  };

  return {
    animals,
    buildings,
    objectives,
    teams,
    list: Object.keys(animals),
  };
});
