(function initPondBalance(root, factory) {
  const balance = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = balance;
  else root.PondBalance = balance;
})(typeof globalThis !== "undefined" ? globalThis : window, function makeBalanceConfig() {
  return {
    expansionBaseMultiplier: 1.08,
    expansionFreeTerritory: 18,
    expansionTerritoryPenalty: 0.1,
    expansionDistancePenalty: 0.08,
    expansionEnemyBorderPenalty: 2.25,
    expansionStrategicPenalty: 1.5,

    baseIncome: 0.95,
    territoryIncome: 0.048,
    terrainIncomeMultiplier: 0.72,
    frogLilyBonus: 0.11,
    duckMaxEnergyPerTile: 0.12,
    turtleBorderDefenseMultiplier: 1.14,
    turtleReedGuardMultiplier: 1.16,
    turtleMudRockAdjDefense: 2,
    turtleExpansionCostMultiplier: 1.08,
    turtleAttackPowerMultiplier: 0.97,
    turtleDefendMultiplier: 1.16,
    shellGuardCaptureCostMultiplier: 1.22,
    shellGuardDefendedExtraMultiplier: 1.08,
    carpWaterIncomeBonus: 0.012,
    carpLilyBonus: 0.105,
    carpConnectedWaterIncomeBonus: 0.004,
    carpLilyFarmCostMultiplier: 0.94,
    carpDefenseMultiplier: 0.92,
    goldenCurrentIncomeMultiplier: 0.24,
    goldenCurrentWaterCostMultiplier: 0.8,
    goldenCurrentLilyCostMultiplier: 0.7,
    maxEnergyBase: 72,
    maxEnergyPerTile: 1.48,
    recoveryIncomeMax: 0.8,
    recoveryTerritoryPct: 0.06,
    lastNestProtectionTerritoryPct: 0.035,
    lastNestProtectionDefense: 18,
    coreExpansionDiscountPct: 0.14,
    empireIncomeSoftCap: 18,
    empireIncomeDamping: 0.06,

    buildTimeSeconds: 10,
    upgradeTimeSeconds: 8,
    buildingCostGrowth: 0.35,
    upgradeCostGrowth: 0.82,
    farmBaseCost: 40,
    farmCostGrowth: 0.42,
    farmIncomeBonus: 0.78,
    farmLilyBonus: 0.18,
    farmFrogBonus: 0.14,
    farmActivationTime: 12,
    farmTerritoryPerFarm: 18,
    farmBorderPenalty: 0.4,
    farmSoftCapTerritory: 16,
    farmSoftCapPenalty: 0.08,

    nestMaxEnergyBonus: 24,
    nestIncomeBonus: 0.08,
    reedGuardIncomeBonus: 0.08,
    mudTunnelIncomeBonus: 0.14,
    jumpPadMaxEnergyBonus: 6,

    defendSpendMultiplier: 0.78,
    defendEnergyMultiplier: 0.58,
    defendCooldownSeconds: 10,
    defendMaxEnergy: 56,
    turtleDefendMaxEnergy: 72,
    defenseDecayPerSecond: 0.45,
    defenseDecayDelaySeconds: 8,
    attackPowerMultiplier: 1.02,
    attackCostMultiplier: 1.02,
    warExhaustionPerAttack: 0.08,
    warExhaustionDecayPerSecond: 0.018,
    maxWarExhaustion: 0.28,
    continuousAttackTickSeconds: 1.45,
    continuousAttackEnergyMultiplier: 0.34,
    continuousAttackMinEnergy: 6,
    continuousAttackMaxPercentPerTick: 0.22,

    supportEfficiency: 0.75,
    supportCooldownSeconds: 14,
    supportMinEnergy: 6,

    flockRushOpenWaterCostMultiplier: 0.65,
    snakeAmbushAttackPowerMultiplier: 1.55,
    snakeAmbushDefenseCostMultiplier: 0.72,
    frogBigLeapClusterSize: 4,
    frogBigLeapRange: 2,
    frogBigLeapJumpPadRange: 3,
    level3DuckDurationBonus: 4,
    level3SnakeCooldownMultiplier: 0.82,
    level3FrogLeapBonus: 1,
    level5DuckWaterCostMultiplier: 0.9,
    level5SnakeReedAttackMultiplier: 1.12,
    level5FrogLilyIncomeMultiplier: 1.22,

    objectiveDefenseBonus: 5,
    objectiveGoldenLilyIncome: 2.2,
    objectiveMudSpringMaxEnergy: 32,
    objectiveCooldownReduction: 0.14,
    objectiveDeepCurrentRoutePower: 1.18,
    campDefenseBonus: 4,
    campAttackMultiplier: 1.12,
    campIncomeBonus: 1.25,
    rainstormWaterCostMultiplier: 0.82,
    lilyBloomIncomeBonus: 0.18,
    mudslideDefenseMultiplier: 1.22,

    botAggressionMultiplier: 1.2,
    botAttackEnergyThreshold: 0.34,
    botAnimalTurnPace: {
      duck: 0.9,
      snake: 1.08,
      frog: 1.04,
      turtle: 1.1,
      carp: 1.03,
    },
    leaderThreatMultiplier: 2.2,
    objectiveSpawnTime: 120,
    lakeEventFirstAt: 150,
    lakeEventInterval: 95,
    midGameTime: 120,
    aggressionTime: 240,
    lateGameTime: 360,
    finalSurgeTime: 480,
    maxMatchTime: 1200,

    coreHealth: 125,
    coreDefenseEnergy: 42,
    coreIncomeBonus: 0.75,
    coreMaxEnergyBonus: 34,
    coreDefenseAuraRange: 3,
    coreDefenseAuraBonus: 7,
    coreLastStandSeconds: 28,
    coreLastStandDefenseBonus: 16,
    coreLostIncomePenalty: 0.72,
    coreLostMaxEnergyPenalty: 0.78,
    surrenderEarliestTime: 330,
    surrenderTerritoryPct: 0.025,
    surrenderEnergyRatio: 0.16,
  };
});
