(function initPondLakeEvents(root, factory) {
  const events = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = events;
  else root.PondLakeEvents = events;
})(typeof globalThis !== "undefined" ? globalThis : window, function makeLakeEvents() {
  return {
    rainstorm: {
      label: "Rainstorm",
      color: "#83dced",
      duration: 30,
      warningLead: 8,
      description: "Open-water neutral expansion is cheaper.",
      areaLabel: "open water",
      warningText: "Storm Front",
      startText: "Rainstorm!",
      endText: "Rainstorm Faded",
      tileTypes: ["water", "lily"],
      visual: "storm",
      intensity: 0.72,
    },
    foggyMarsh: {
      label: "Foggy Marsh",
      color: "#b3c6cc",
      duration: 30,
      warningLead: 8,
      description: "Enemy strength estimates are hidden.",
      areaLabel: "marsh edge",
      warningText: "Mist Settles In",
      startText: "Foggy Marsh!",
      endText: "Mist Lifted",
      tileTypes: ["reeds", "mud", "lily"],
      visual: "fog",
      intensity: 0.58,
    },
    lilyBloom: {
      label: "Lily Bloom",
      color: "#86d68d",
      duration: 45,
      warningLead: 7,
      description: "Lily pads give extra income.",
      areaLabel: "lily pads",
      warningText: "Lily Bloom",
      startText: "Lily Bloom!",
      endText: "Bloom Faded",
      tileTypes: ["lily"],
      visual: "lily",
      intensity: 0.78,
    },
    mudslide: {
      label: "Mud Slide",
      color: "#c39a62",
      duration: 30,
      warningLead: 9,
      description: "Mud tiles become stronger defensive ground.",
      areaLabel: "mud banks",
      warningText: "Mud Slide Incoming!",
      startText: "Mud Slide!",
      endText: "Mud Slide Ended",
      tileTypes: ["mud"],
      visual: "mud",
      intensity: 0.88,
    },
    migration: {
      label: "Migration",
      color: "#d8ad48",
      duration: 35,
      warningLead: 7,
      description: "Neutral critter camps refresh around the lake.",
      areaLabel: "critter camps",
      warningText: "Critters On The Move",
      startText: "Migration!",
      endText: "Migration Settled",
      tileTypes: ["nest", "lily", "reeds"],
      visual: "migration",
      intensity: 0.74,
    },
    floodWave: {
      label: "Flood Wave",
      color: "#8bdfff",
      duration: 28,
      warningLead: 8,
      description: "A strong water surge makes open-water routes easier to read.",
      areaLabel: "main channel",
      warningText: "Flood Wave Approaching!",
      startText: "Flood Wave!",
      endText: "Flood Wave Passed",
      tileTypes: ["water"],
      visual: "flood",
      directional: true,
      intensity: 0.86,
    },
    reedSurge: {
      label: "Reed Surge",
      color: "#8ddf96",
      duration: 34,
      warningLead: 7,
      description: "Reeds sway hard and border defense signals are easier to spot.",
      areaLabel: "reed beds",
      warningText: "Reed Surge",
      startText: "Reed Surge!",
      endText: "Reeds Settled",
      tileTypes: ["reeds"],
      visual: "reed",
      intensity: 0.76,
    },
    currentShift: {
      label: "Current Shift",
      color: "#4fd4cf",
      duration: 32,
      warningLead: 8,
      description: "Visible currents show the lake flow direction.",
      areaLabel: "current lane",
      warningText: "Current Shift!",
      startText: "Current Shift!",
      endText: "Current Calmed",
      tileTypes: ["water", "lily"],
      visual: "current",
      directional: true,
      intensity: 0.8,
    },
    rockfall: {
      label: "Rockfall",
      color: "#b8a69a",
      duration: 26,
      warningLead: 8,
      description: "Loose stones mark blocked channels and rocky choke points.",
      areaLabel: "rocky channel",
      warningText: "Rockfall Warning!",
      startText: "Rockfall Blocked The Channel!",
      endText: "Channel Reopened",
      tileTypes: ["rock"],
      visual: "rock",
      intensity: 0.72,
    },
    jungleRain: {
      label: "Jungle Rain",
      color: "#72d59a",
      duration: 32,
      warningLead: 8,
      description: "Heavy warm rain brightens jungle channels and boosts open-water expansion clarity.",
      areaLabel: "jungle channels",
      warningText: "Jungle Rain Building",
      startText: "Jungle Rain!",
      endText: "Jungle Rain Faded",
      tileTypes: ["water", "reeds", "mud"],
      visual: "storm",
      intensity: 0.8,
    },
    canalSurge: {
      label: "Canal Surge",
      color: "#73d6d1",
      duration: 30,
      warningLead: 8,
      description: "Canal currents become visible through the delta maze.",
      areaLabel: "canal lanes",
      warningText: "Canal Surge",
      startText: "Canal Surge!",
      endText: "Canals Calmed",
      tileTypes: ["water", "lily"],
      visual: "current",
      directional: true,
      intensity: 0.82,
    },
    sandWind: {
      label: "Sand Wind",
      color: "#d2b071",
      duration: 30,
      warningLead: 8,
      description: "Warm wind rolls over blocked desert banks and marks dangerous chokepoints.",
      areaLabel: "desert banks",
      warningText: "Sand Wind Rising",
      startText: "Sand Wind!",
      endText: "Sand Wind Settled",
      tileTypes: ["desert", "rock"],
      visual: "fog",
      intensity: 0.62,
    },
    floodPulse: {
      label: "Flood Pulse",
      color: "#8bdfff",
      duration: 28,
      warningLead: 8,
      description: "A fast pulse rolls down the river and highlights long-water routes.",
      areaLabel: "river spine",
      warningText: "Flood Pulse Approaching",
      startText: "Flood Pulse!",
      endText: "Flood Pulse Passed",
      tileTypes: ["water", "lily"],
      visual: "flood",
      directional: true,
      intensity: 0.84,
    },
    oasisBloom: {
      label: "Oasis Bloom",
      color: "#e3bd4f",
      duration: 36,
      warningLead: 7,
      description: "Oasis lilies bloom and become more valuable to fight over.",
      areaLabel: "oasis pools",
      warningText: "Oasis Bloom",
      startText: "Oasis Bloom!",
      endText: "Oasis Bloom Faded",
      tileTypes: ["lily", "water"],
      visual: "lily",
      intensity: 0.76,
    },
  };
});
