(function initPondBotDifficulty(root, factory) {
  const config = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = config;
  else root.PondBotDifficulty = config;
})(typeof globalThis !== "undefined" ? globalThis : window, function makeBotDifficultyConfig() {
  return {
    passive: {
      label: "Passive",
      description: "Sandbox/testing only. Does not expand or attack unless directly commanded.",
      reactionDelay: [999, 999],
      thinkInterval: [999, 999],
      turnPaceMultiplier: 999,
      expansionDelay: [999, 999],
      expansionAggression: 0,
      expansionMultiplier: 0,
      expandCooldown: [999, 999],
      attackCooldown: [999, 999],
      defenseCooldown: [999, 999],
      currentPushCooldown: 999,
      currentPushChance: 0,
      mistakeChance: 1,
      defenseMistakeChance: 1,
      aggression: 0,
      attackPercentMultiplier: 0,
      minimumAttackSpend: 999,
      specialChance: 0,
      specialCooldown: [999, 999],
      specialEarliestTime: Infinity,
      beginnerCombat: true,
    },
    easy: {
      label: "Easy",
      description: "Beginner friendly. Slow expansion, delayed reactions, frequent mistakes, rare attacks, no early specials.",
      reactionDelay: [8, 12],
      thinkInterval: [1.5, 2.5],
      turnPaceMultiplier: 2.15,
      expansionDelay: [5, 8],
      expansionAggression: 0.45,
      expansionMultiplier: 0.45,
      expandCooldown: [5, 8],
      attackCooldown: [20, 30],
      defenseCooldown: [18, 28],
      currentPushCooldown: 110,
      currentPushChance: 0.002,
      mistakeChance: 0.45,
      defenseMistakeChance: 0.45,
      aggression: 0.28,
      attackPercentMultiplier: 0.62,
      minimumAttackSpend: 20,
      maxEarlyExpansionSend: 0.25,
      buildMultiplier: 0.45,
      specialChance: 0,
      specialCooldown: [95, 130],
      specialEarliestTime: 480,
      beginnerCombat: true,
    },
    normal: {
      label: "Normal",
      description: "Fair pressure. Slower than a strong player, sometimes wrong, and rare specials after mid-game.",
      reactionDelay: [5, 8],
      thinkInterval: [1.0, 1.8],
      turnPaceMultiplier: 1.42,
      expansionDelay: [3, 6],
      expansionAggression: 0.7,
      expansionMultiplier: 0.7,
      expandCooldown: [3, 6],
      attackCooldown: [14, 22],
      defenseCooldown: [14, 22],
      currentPushCooldown: 86,
      currentPushChance: 0.025,
      mistakeChance: 0.25,
      defenseMistakeChance: 0.25,
      aggression: 0.48,
      attackPercentMultiplier: 0.74,
      minimumAttackSpend: 19,
      maxEarlyExpansionSend: 0.5,
      buildMultiplier: 0.72,
      specialChance: 0.012,
      specialCooldown: [95, 135],
      specialEarliestTime: 210,
      beginnerCombat: false,
    },
    smart: {
      label: "Hard",
      description: "Smarter combat. Faster reactions, stronger attacks, occasional Current Push.",
      reactionDelay: [3, 5],
      thinkInterval: [0.6, 1.2],
      turnPaceMultiplier: 1.02,
      expansionDelay: [2, 4],
      expansionAggression: 0.9,
      expansionMultiplier: 0.9,
      expandCooldown: [2, 4],
      attackCooldown: [9, 16],
      defenseCooldown: [9, 15],
      currentPushCooldown: 62,
      currentPushChance: 0.075,
      mistakeChance: 0.1,
      defenseMistakeChance: 0.1,
      aggression: 0.92,
      attackPercentMultiplier: 0.94,
      minimumAttackSpend: 11,
      maxEarlyExpansionSend: 0.65,
      buildMultiplier: 0.92,
      specialChance: 0.055,
      specialCooldown: [68, 95],
      specialEarliestTime: 120,
      beginnerCombat: false,
    },
    chaos: {
      label: "Chaos",
      description: "Advanced only. Frequent wars, fast reactions, more Current Push pressure.",
      reactionDelay: [1, 3],
      thinkInterval: [0.4, 0.8],
      turnPaceMultiplier: 0.76,
      expansionDelay: [0.8, 2],
      expansionAggression: 1.1,
      expansionMultiplier: 1.1,
      expandCooldown: [0.8, 2],
      attackCooldown: [4, 8],
      defenseCooldown: [5, 8],
      currentPushCooldown: 40,
      currentPushChance: 0.16,
      mistakeChance: 0.05,
      defenseMistakeChance: 0.05,
      aggression: 1.35,
      attackPercentMultiplier: 1.08,
      minimumAttackSpend: 9,
      maxEarlyExpansionSend: 0.85,
      buildMultiplier: 1,
      specialChance: 0.12,
      specialCooldown: [46, 70],
      specialEarliestTime: 75,
      beginnerCombat: false,
    },
  };
});
