(function initPondObjectives(root, factory) {
  const objectives = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = objectives;
  else root.PondObjectives = objectives;
})(typeof globalThis !== "undefined" ? globalThis : window, function makeObjectives() {
  const LAKE_OBJECTIVES = {
    goldenLily: {
      label: "Golden Lily",
      short: "GL",
      color: "#e3bd4f",
      spawn: { x: 42, y: 27, radius: 5 },
      tilePreference: ["lily", "water", "nest"],
      captureCostBonus: 26,
      incomeBonus: 2.2,
      xp: 22,
      description: "Bonus income while controlled.",
    },
    ancientReed: {
      label: "Ancient Reed",
      short: "AR",
      color: "#91c579",
      spawn: { x: 22, y: 15, radius: 6 },
      tilePreference: ["reeds", "mud", "water"],
      captureCostBonus: 24,
      defenseBonus: 5,
      xp: 20,
      description: "Adds border defense to your whole front.",
    },
    mudSpring: {
      label: "Mud Spring",
      short: "MS",
      color: "#c39a62",
      spawn: { x: 64, y: 39, radius: 6 },
      tilePreference: ["mud", "nest", "reeds"],
      captureCostBonus: 28,
      maxEnergyBonus: 32,
      xp: 20,
      description: "Increases maximum Animal Energy.",
    },
    clearWaterShrine: {
      label: "Clear Water Shrine",
      short: "CW",
      color: "#83dced",
      spawn: { x: 60, y: 15, radius: 6 },
      tilePreference: ["water", "lily", "nest"],
      captureCostBonus: 24,
      cooldownReduction: 0.14,
      xp: 22,
      description: "Reduces animal ability cooldowns.",
    },
    deepCurrent: {
      label: "Deep Current",
      short: "DC",
      color: "#6fb8f0",
      spawn: { x: 42, y: 40, radius: 7 },
      tilePreference: ["water", "lily", "reeds"],
      captureCostBonus: 25,
      routePowerBonus: 0.18,
      xp: 22,
      description: "Improves Current Push water-route attacks.",
    },
    goldenLilyBasin: {
      label: "Golden Lily Basin",
      short: "GB",
      color: "#e3bd4f",
      spawn: { x: 42, y: 27, radius: 7 },
      tilePreference: ["lily", "water", "nest"],
      captureCostBonus: 28,
      incomeBonus: 2.4,
      xp: 24,
      description: "A bright lily basin that rewards income control.",
    },
    ancientReedWall: {
      label: "Ancient Reed Wall",
      short: "RW",
      color: "#91c579",
      spawn: { x: 22, y: 15, radius: 7 },
      tilePreference: ["reeds", "mud", "water"],
      captureCostBonus: 26,
      defenseBonus: 6,
      xp: 22,
      description: "Old reed walls strengthen borders while controlled.",
    },
    canalGate: {
      label: "Canal Gate",
      short: "CG",
      color: "#83dced",
      spawn: { x: 42, y: 27, radius: 5 },
      tilePreference: ["water", "reeds", "mud"],
      captureCostBonus: 25,
      routePowerBonus: 0.18,
      xp: 22,
      description: "Controls canal flow and improves route pressure.",
    },
    lotusField: {
      label: "Lotus Field",
      short: "LF",
      color: "#86d68d",
      spawn: { x: 30, y: 18, radius: 6 },
      tilePreference: ["lily", "water", "reeds"],
      captureCostBonus: 24,
      incomeBonus: 2.1,
      xp: 22,
      description: "A dense lotus field with strong income value.",
    },
    mudMarket: {
      label: "Mud Market",
      short: "MM",
      color: "#c39a62",
      spawn: { x: 58, y: 38, radius: 6 },
      tilePreference: ["mud", "water", "reeds"],
      captureCostBonus: 26,
      maxEnergyBonus: 28,
      xp: 20,
      description: "A muddy delta hub that increases maximum Animal Energy.",
    },
    riverShrine: {
      label: "River Shrine",
      short: "RS",
      color: "#83dced",
      spawn: { x: 64, y: 16, radius: 6 },
      tilePreference: ["nest", "water", "lily"],
      captureCostBonus: 24,
      cooldownReduction: 0.14,
      xp: 22,
      description: "A shrine that speeds up animal ability recovery.",
    },
    mistyReed: {
      label: "Misty Reed",
      short: "MR",
      color: "#b3c6cc",
      spawn: { x: 42, y: 18, radius: 7 },
      tilePreference: ["reeds", "lily", "mud"],
      captureCostBonus: 26,
      defenseBonus: 5,
      xp: 22,
      description: "A foggy reed objective with strong defensive value.",
    },
    turtleCampObjective: {
      label: "Turtle Camp",
      short: "TC",
      color: "#91b978",
      spawn: { x: 25, y: 35, radius: 7 },
      tilePreference: ["mud", "reeds", "nest"],
      captureCostBonus: 26,
      defenseBonus: 6,
      xp: 22,
      description: "A durable swamp camp that helps borders survive pushes.",
    },
    dragonflySwarmObjective: {
      label: "Dragonfly Swarm",
      short: "DS",
      color: "#b58be0",
      spawn: { x: 42, y: 27, radius: 7 },
      tilePreference: ["lily", "water", "reeds"],
      captureCostBonus: 24,
      cooldownReduction: 0.1,
      xp: 22,
      description: "A shimmering swarm that supports ability and defense play.",
    },
    oasisShrine: {
      label: "Oasis Shrine",
      short: "OS",
      color: "#83dced",
      spawn: { x: 28, y: 16, radius: 6 },
      tilePreference: ["lily", "water", "nest"],
      captureCostBonus: 26,
      cooldownReduction: 0.14,
      xp: 22,
      description: "A desert oasis shrine that rewards clean river control.",
    },
    crocodileRock: {
      label: "Crocodile Rock",
      short: "CR",
      color: "#b8a69a",
      spawn: { x: 52, y: 24, radius: 6 },
      tilePreference: ["mud", "reeds", "water"],
      captureCostBonus: 30,
      defenseBonus: 6,
      xp: 22,
      description: "A rocky chokepoint objective with high defensive pressure.",
    },
    goldenLotus: {
      label: "Golden Lotus",
      short: "GT",
      color: "#e3bd4f",
      spawn: { x: 40, y: 34, radius: 6 },
      tilePreference: ["lily", "water", "nest"],
      captureCostBonus: 27,
      incomeBonus: 2.3,
      xp: 24,
      description: "A golden lotus that powers late-game economy.",
    },
    riverGate: {
      label: "River Gate",
      short: "RG",
      color: "#91c579",
      spawn: { x: 45, y: 42, radius: 6 },
      tilePreference: ["reeds", "water", "mud"],
      captureCostBonus: 26,
      routePowerBonus: 0.16,
      xp: 22,
      description: "A narrow gate that improves river route pressure.",
    },
  };

  const CRITTER_CAMPS = {
    turtleCamp: {
      label: "Turtle Camp",
      short: "TC",
      color: "#91b978",
      positions: [
        { x: 16, y: 25 },
        { x: 68, y: 31 },
      ],
      captureCostBonus: 18,
      duration: 70,
      effect: "defense",
      xp: 12,
      description: "Temporary border defense after capture.",
    },
    crabCamp: {
      label: "Crab Camp",
      short: "CC",
      color: "#df806d",
      positions: [
        { x: 31, y: 14 },
        { x: 54, y: 41 },
      ],
      captureCostBonus: 18,
      duration: 60,
      effect: "attack",
      xp: 12,
      description: "Temporary attack bonus after capture.",
    },
    otterCamp: {
      label: "Otter Camp",
      short: "OC",
      color: "#d2a769",
      positions: [
        { x: 31, y: 40 },
        { x: 54, y: 14 },
      ],
      captureCostBonus: 16,
      duration: 75,
      effect: "income",
      xp: 12,
      description: "Temporary income bonus after capture.",
    },
    dragonflySwarm: {
      label: "Dragonfly Swarm",
      short: "DS",
      color: "#b58be0",
      positions: [
        { x: 42, y: 17 },
        { x: 42, y: 38 },
      ],
      captureCostBonus: 15,
      duration: 75,
      effect: "vision",
      xp: 12,
      description: "Temporary scouting clarity after capture.",
    },
  };

  return {
    LAKE_OBJECTIVES,
    CRITTER_CAMPS,
  };
});
